server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: C:\\Toolbox\\cms-service-repo
          cloneOnStart: true

  profiles:
    active: development
management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: "*"